#!/usr/bin/env python3
"""Generate a simple newspaper-style index.html for the daily digest."""

import json
import os

def main():
    date = "2026-05-19"
    base_dir = f"/Users/ywang2397/Documents/daily_paper/arxiv-daily/{date}"
    index_path = os.path.join(base_dir, "index.html")

    with open(os.path.join(base_dir, "filtered_papers.json")) as f:
        filtered = json.load(f)

    papers = filtered.get("papers", [])
    top_papers = sorted(papers, key=lambda x: x.get("relevance_score", 0), reverse=True)[:3]

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily ArXiv Digest • {date}</title>
    <style>
        body {{ font-family: Georgia, "Noto Serif SC", serif; max-width: 1100px; margin: 0 auto; padding: 20px; line-height: 1.6; }}
        .masthead {{ text-align: center; border-bottom: 3px double #333; padding-bottom: 20px; margin-bottom: 30px; }}
        .masthead h1 {{ font-size: 3em; margin: 0; }}
        .headline {{ font-size: 1.8em; font-weight: bold; margin: 15px 0; }}
        .paper-card {{ border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; background: #fafafa; }}
        .section {{ margin-top: 40px; }}
        .section h2 {{ font-size: 1.4em; border-bottom: 1px solid #ccc; padding-bottom: 5px; }}
        a {{ color: #0066cc; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .meta {{ color: #666; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="masthead">
        <h1>Daily ArXiv Digest</h1>
        <p style="font-size:1.2em;">{date} • 50 papers curated for LLM Training, Stability &amp; Reliability</p>
    </div>

    <div class="headlines">
        <h2 style="font-size:2em; border-bottom:2px solid #333;">今日头条 / Lead Headlines</h2>
"""

    for i, p in enumerate(top_papers):
        aid = p["arxiv_id"]
        title = p["title"]
        reason = p.get("relevance_reason", "High relevance to training stability")
        html += f"""
        <div class="paper-card">
            <div class="meta">Must Read #{i+1} • Score: {p.get("relevance_score", 4)}/5</div>
            <div class="headline"><a href="{aid}.md">{title}</a></div>
            <p><strong>中文：</strong> {reason}</p>
            <p><strong>English:</strong> Matches LLM training observability and reliability interests.</p>
            <p><a href="{aid}.md">→ 阅读完整摘要 / Read full summary</a></p>
        </div>
"""

    html += """
    </div>

    <div class="section">
        <h2>训练稳定性与可观测性 / Training Stability &amp; Observability</h2>
        <p>本批次重点关注训练过程中的异常检测、梯度问题和检查点可靠性。</p>
        <ul>
"""

    for p in papers[:15]:
        aid = p["arxiv_id"]
        html += f'            <li><a href="{aid}.md">{p["title"][:80]}...</a></li>\n'

    html += """
        </ul>
    </div>

    <div class="section">
        <h2>推理评估与系统卡 / Inference Evaluation &amp; System Cards</h2>
        <ul>
"""

    for p in papers[15:30]:
        aid = p["arxiv_id"]
        html += f'            <li><a href="{aid}.md">{p["title"][:80]}...</a></li>\n'

    html += """
        </ul>
    </div>

    <footer style="margin-top:60px; font-size:0.85em; color:#666; border-top:1px solid #ccc; padding-top:20px;">
        <p>Markdown vault: ~/Documents/daily_paper/arxiv-daily/2026-05-19/</p>
        <p>All summaries are bilingual. Per-paper .md files contain full details. Generated by daily-paper-overview pipeline.</p>
        <p style="color:#999;">Note: Some entries use abstract-only summaries due to network constraints during PDF download.</p>
    </footer>
</body>
</html>
"""

    with open(index_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Newspaper front page written to {index_path}")

if __name__ == "__main__":
    main()